const images = {
  logo: require('../assets/images/logo.png'),
  speechBubble: require('../assets/images/speechBubble.png'),
  bigBubble: require('../assets/images/bigBubble.png'),
  back: require('../assets/images/back.png'),
  backSignin: require('../assets/images/closeSignin.png'),
  callButton: require('../assets/images/callButton.png'),
  questionMark: require('../assets/images/questionMark.png'),
  close: require('../assets/images/close.png'),
  closeLargeIcon:require('../assets/images/closeLarge.png'),
  sync: require('../assets/images/sync.png'),
  fingerprint: require('../assets/images/fingerprint.png'),
  topNavBar: require('../assets/images/topNavBar.png'),
  bottomNavBar: require('../assets/images/bottomNavBar.png'),
  home: require('../assets/images/home.png'),
  message: require('../assets/images/message.png'),
  notification: require('../assets/images/notification.png'),
  tasks: require('../assets/images/tasks.png'),
  flash: require('../assets/images/flash.png'),
  filter: require('../assets/images/filter.png'),
  checkmark: require('../assets/images/checkmark.png'),
  exclamation: require('../assets/images/exclamation.png'),
  triangle: require('../assets/images/triangle.png'),
  camera: require('../assets/images/camera.png'),
  beacon: require('../assets/images/beacon.png'),
  warningTriangle: require('../assets/images/warningTriangle.png'),
  class: require('../assets/images/class.png'),
  trash: require('../assets/images/trash.png'),
  device: require('../assets/images/device.png'),
  teacher: require('../assets/images/teacher.png'),
  rightArrow: require('../assets/images/right-arrow.png'),
  barChart: require('../assets/images/barChart.png'),
  checkmarkSquare: require('../assets/images/checkmarkSquare.png'),
  history: require('../assets/images/history.png'),
  clock: require('../assets/images/clock.png'),
  search: require('../assets/images/search.png'),
  globe: require('../assets/images/globe.png'),
  downArrow: require('../assets/images/down-arrow.png'),
  refresh: require('../assets/images/refresh.png'),
  globe2: require('../assets/images/globe-2.png'),
  radioButtonOff: require('../assets/images/radioButtonOff.png'),
  radioButtonOn: require('../assets/images/radioButtonOn.png'),
  checkCircle: require('../assets/images/check-circle.png'),
  crossCircle: require('../assets/images/cross-circle.png'),
  schoolCircle: require('../assets/images/school-circle.png'),
  questionCircle: require('../assets/images/question-circle.png'),
  exclamationCircle: require('../assets/images/exclamation-circle.png'),
  play: require('../assets/images/play.png'),
  book: require('../assets/images/book.png'),

  welcomeBG: require('../assets/images/welcomeBG.png'),
  logoWithText:require('../assets/images/logoWithText.png'),
  catBeauty:require('../assets/images/category1.png'),
  catFitness:require('../assets/images/category3.png'),
  catGarden:require('../assets/images/category2.png'),
  catPets:require('../assets/images/category4.png'),
  catTaxi:require('../assets/images/category2.png'),


  bottomTabExplore: require('../assets/images/exploreTab.png'),
  bottomTabFavourite: require('../assets/images/favouriteTab.png'),
  bottomTabAppointment: require('../assets/images/appointmentTab.png'),
  bottomTabSettings: require('../assets/images/settingTab.png'),
  
  mapViewIcon: require('../assets/images/mapView.png'),
  vendorProfilePic1: require('../assets/images/profile1.png'),
  vendorProfilePic2: require('../assets/images/profile2.png'),
  starRating: require('../assets/images/rating.png'),
  reviewsRating: require('../assets/images/starRating.png'),
  noDetails:require('../assets/images/noDetails.png'),
  slider1: require('../assets/images/slider1.png'),
  customerImage: require('../assets/images/cutomerImage.png'),
  toilets: require('../assets/images/toilets.png'),
  babyChanging: require('../assets/images/baby-changing-area.png'),
  handWashing: require('../assets/images/hand-washing.png'),
  airConditioning: require('../assets/images/air-conditing.png'),
  freeParking: require('../assets/images/free-parking.png'),
  waitingArea: require('../assets/images/waiting-area.png'),
  callIocn: require('../assets/images/call.png'),
  instaIocn: require('../assets/images/instagram.png'),

  detailHeaderImg: require('../assets/images/detailHeaderImg.png'),
  arrowUp:require('../assets/images/arrow-up.png'),
  arrowDown:require('../assets/images/arrow-down.png'),
  filterIcon:require('../assets/images/filterIcon.png'),
  google:require('../assets/images/google.png'),
  password:require('../assets/images/password.png'),
  cancel:require('../assets/images/cancel.png'),
  user:require('../assets/images/user.png'),
  confirm:require('../assets/images/confirm.png'),
  creditCard:require('../assets/images/creditcard.png'),
  paypal:require('../assets/images/paypal.png'),
  personalDetails:require('../assets/images/personalDetails.png'),
  userProfilePic:require('../assets/images/userProfilePic.png'),
// icons
  homeimg:require('../assets/images/icons/home-alt.png'),
  receipt:require('../assets/images/icons/receipt.png'),
  aboutUs:require('../assets/images/icons/aboutUs.png'),
  chat:require('../assets/images/icons/chat.png'),
  help:require('../assets/images/icons/help.png'),
  legal:require('../assets/images/icons/legal.png'),
  logout:require('../assets/images/icons/logout.png'),
  payments:require('../assets/images/icons/payments.png'),
  settingsPersonalDetails:require('../assets/images/icons/persnalDetails.png'),
  reviews:require('../assets/images/icons/reviews.png'),
  setting:require('../assets/images/icons/setting.png'),
  switch:require('../assets/images/icons/switch.png'),
  waiting:require('../assets/images/icons/waiting.png'),

  send:require('../assets/images/icons/send.png'),

  chatBG:require('../assets/images/chat-bg.png'),

  clearFilter:require('../assets/images/icons/clearfilter.png'),
  visa:require('../assets/images/visa.png'),
  nextAppointment:require('../assets/images/icons/appointment.png'),
  serviceType:require('../assets/images/icons/service.png'),
  booking:require('../assets/images/icons/booking.png'),
  showservice:require('../assets/images/icons/showservice.png'),
  babyChangingArea:require('../assets/images/icons/babychanging.png'),
  disabled:require('../assets/images/icons/disabled.png'),
  parking:require('../assets/images/icons/parking.png'),
  shopImage:require('../assets/images/shopImage.png'),
  favoruite: require ('../assets/images/favoruite.png'),
  addCalendar: require ('../assets/images/addCalendar.png'),
  mapPin: require ('../assets/images/Vector.png'),
  mapPinSM: require('../assets/images/pin-small.png'),
  mapPinMD: require('../assets/images/pin-md.png'),
  payCash: require('../assets/images/payCash.png'),

  notificationIcon:require('../assets/images/icons/notification.png'),
  languageIcon: require('../assets/images/icons/language.png'),
  currencyIcon: require('../assets/images/icons/country.png'),
  appPermissionIcon: require('../assets/images/icons/appPermission.png'),
  appversionIocn: require('../assets/images/icons/appversion.png'),
  goToIcon: require('../assets/images/icons/goTo.png'),
};

export default images;
